// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

static const FirebaseOptions android = FirebaseOptions(
  apiKey: 'AIzaSyBLsuFQwthPzSKqKnJMCYV1eh4qRFgu1V4',
  appId: '1:697404483084:android:06edceb161b3df36467029',
  messagingSenderId: '697404483084',
  projectId: 'footspots-8f8d3',
  databaseURL: 'https://footspots-8f8d3-default-rtdb.firebaseio.com',
  storageBucket: 'footspots-8f8d3.firebasestorage.app',
);


  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFfLXu0-YxQeDNgEtEoIA6ockFVkTvwA4',
    appId: '1:697404483084:ios:8bfec2874442cf5d467029',
    messagingSenderId: '697404483084',
    projectId: 'footspots-8f8d3',
    databaseURL: 'https://footspots-8f8d3-default-rtdb.firebaseio.com',
    storageBucket: 'footspots-8f8d3.firebasestorage.app',
    androidClientId: '697404483084-414stqm01eiopc8lb40os6q1ls3aqmhb.apps.googleusercontent.com',
    iosClientId: '697404483084-9gfd19s8q5ilmgos9uspaefvovofseeo.apps.googleusercontent.com',
    iosBundleId: 'com.foodspots.customer',
  );
}
